# Generated by Django 3.1.3 on 2022-03-31 09:07

from django.conf import settings
from django.db import migrations, models
import insta.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=insta.fields.ThumbnailImageField(null=True, upload_to='insta/%Y/%m', verbose_name='IMAGE'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='voter',
            field=models.ManyToManyField(related_name='voter_photo', to=settings.AUTH_USER_MODEL),
        ),
    ]
